---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - pip install ansible-lint

script:
  - ansible-lint inventory.yml
  - ansible-playbook -i inventory.yml playbook.yml --syntax-check
  - "ansible-playbook -i inventory.yml playbook.yml --connection=local --sudo"
